### ISSUE TITLE
Jasmine gps_stats_main: HTTPSConnectionPool: Read timed out.

### ISSUE THREAD

**Issue by eolson730** [onnela-lab/forest#124]
[new to GitHub, sorry for any etiquette errors here].

I'm trying to run gps_stats_main:

gps_stats_main(path_to_gps_data, path_to_gps_summary, tz_str, frequency, save_traj, parameters, save_log, threshold)
User: XXX
Read in the csv files ...
Collapse data within 10 second intervals ...
Extract flights and pauses ...
Infer unclassified windows ...
Merge consecutive pauses and bridge gaps ...
Selecting basis vectors ...
Imputing missing trajectories ...
Tidying up the trajectories...

And then I get a bunch of timeout errors, ending in:

raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='overpass-api.de', port=443): Read timed out. (read timeout=60)   

Saw some similar probs previously reported but it looked like they had been resolved so I'm not sure what my issue is here, any pointers much appreciated.

**Comment by GeorgeEfstathiadis** [comment]
So this happens when trying to parse a lot of data through OpenStreetMaps. When you have `save_log = True` you are asking the algorithm to go through your excel file and return all possible nearby locations to your coordinates for the entire time of observation. If you travel a large amount of space or for a long amount of time the data returned will be overwhelmingly a lot and OpenStreetMaps will not be able to handle it. 

Unfortunately that is not an easy issue to fix in a concise way, since it has to do with the large amounts of data returned from the API. If you want to get a log of all the locations visited a possible solution could be to split your excel files into different folders and pass each of them through the algorithm separately.

**Comment by clementzach** [comment]
Hmm. 

In the past, I've gotten around API errors like this by putting a try/except inside of a while loop. 

We could also just catch the exception and return a more user-friendly error message. Something like "only use save_log = True if you're actually interested in openstreetmaps locations"

And, we could also perhaps change the save_log argument name to save_openstreetmaps_log to keep people from using it when they don't actually need those logs. 

Let me know if you would like me to put in some work on this. I'll have more bandwidth once my internship ends in mid-august.

**Comment by GeorgeEfstathiadis** [comment]
These sound like good ideas to me. When you have time to implement them we can create a pull request and link it to this issue.
