### ISSUE TITLE
Deprecation warning for frame.append method in simulate_gps_data.py

### ISSUE THREAD

**Issue by hackdna** [onnela-lab/forest#91]
Commit: [80cc7ff](https://github.com/onnela-lab/forest/commit/80cc7ff176ab7d73d2b09efcb87ff53de016d8cb)

Steps to reproduce:
```
pytest
```

Observed results:
```
forest/bonsai/tests/test_simulate_gps_data.py::test_sim_gps_data_times
forest/bonsai/tests/test_simulate_gps_data.py::test_sim_gps_data_multiple_people
forest/bonsai/tests/test_simulate_gps_data.py::test_sim_gps_data_multiple_people
forest/bonsai/tests/test_simulate_gps_data.py::test_sim_gps_data_multiple_people
  /Users/ils475/code/forest-private/forest/bonsai/simulate_gps_data.py:1389: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
    gps_data = gps_data.append(obs_pd)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

Expected results:
No warnings or errors

**Comment by clementzach** [comment]
@hackdna if I were to implement a fix for this, I know I would need to implement mypy and make common_funcs.py PEP 8 compliant. 

Would I also need to implement mypy/PEP8 for the rest of poplar? And would I need to implement new tests for the functions in poplar?

The fix is very simple, and I'm pretty annoyed with the warning (it keeps producing too much output and making my jupyter notebooks take forever to load). I'm just not sure if this is something I would be able to fix now or if it would need to wait until I have more time.

**Comment by clementzach** [comment]
Actually, I double checked, and the error in Poplar is a separate error. 

I pushed a fix for this one. At least on my machine, this stops the error that happens when running pytest.

**Comment by hackdna** [comment]
Great! Btw, you can always check the Actions output to see if the issue was fixed not just on your machine :)
https://github.com/onnela-lab/forest/actions
